import React from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, Linking } from 'react-native';
import ErrorBoundary from './ErrorBoundary';

const SOURCES = [
  {
    name: 'WHO Guidelines on Physical Activity and Sedentary Behaviour',
    org: 'World Health Organization',
    url: 'https://www.who.int/publications/i/item/9789240015128',
  },
  {
    name: 'Dietary Guidelines for Americans, 2020–2025',
    org: 'U.S. Department of Agriculture & HHS',
    url: 'https://www.dietaryguidelines.gov/',
  },
  {
    name: 'Physical Activity Guidelines Resources',
    org: 'American College of Sports Medicine (ACSM)',
    url: 'https://acsm.org/education-resources/trending-topics-resources/physical-activity-guidelines/',
  },
  {
    name: 'Physical Activity Basics',
    org: 'Centers for Disease Control and Prevention (CDC)',
    url: 'https://www.cdc.gov/physical-activity-basics/',
  },
  {
    name: 'Position Stand: Protein and Exercise',
    org: 'International Society of Sports Nutrition (ISSN)',
    url: 'https://pubmed.ncbi.nlm.nih.gov/28642676/',
  },
];

function SourcesScreenInner({ navigation }) {
  return (
    <View style={styles.container}>
      <View style={styles.header}>
        <TouchableOpacity onPress={() => navigation.goBack()}>
          <Text style={styles.back}>← Back</Text>
        </TouchableOpacity>
        <Text style={styles.title}>Sources & Disclaimer</Text>
      </View>
      <ScrollView contentContainerStyle={styles.content}>
        <Text style={styles.section}>Medical Disclaimer</Text>
        <Text style={styles.body}>
          KineticIQ provides general fitness and nutrition information for educational purposes only. It is not medical advice, and the AI Coach is not a medical professional. Always consult your physician or another qualified health provider before starting a new exercise program or changing your diet, especially if you have a medical condition, are pregnant, or take medication.{'\n\n'}
          Never disregard professional medical advice or delay seeking it because of something you read in this app. If you experience pain, dizziness, or shortness of breath while exercising, stop immediately and seek medical attention.
        </Text>

        <Text style={styles.section}>Our Sources</Text>
        <Text style={styles.body}>
          The workout plans, nutrition targets, and coaching guidance in KineticIQ are informed by published guidelines and research from leading health organizations. Tap any source to read it:
        </Text>

        {SOURCES.map((source, i) => (
          <TouchableOpacity key={i} style={styles.sourceCard} onPress={() => Linking.openURL(source.url)}>
            <Text style={styles.sourceName}>{source.name}</Text>
            <Text style={styles.sourceOrg}>{source.org}</Text>
            <Text style={styles.sourceLink}>{source.url}</Text>
          </TouchableOpacity>
        ))}

        <Text style={styles.section}>About AI-Generated Guidance</Text>
        <Text style={styles.body}>
          Your plans and coaching responses are generated by AI based on the information you provide and the guidelines above. AI-generated recommendations are general in nature and may not account for your complete health picture. Use your judgment and your doctor's advice first.
        </Text>

        <View style={styles.spacer} />
      </ScrollView>
    </View>
  );
}

const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: '#080C10' },
  header: { paddingTop: 60, paddingHorizontal: 20, paddingBottom: 16, borderBottomWidth: 1, borderBottomColor: 'rgba(255,255,255,0.07)' },
  back: { color: '#00E5A0', fontSize: 15, fontWeight: '600', marginBottom: 8 },
  title: { fontSize: 28, fontWeight: '800', color: '#F0F4F8', letterSpacing: -0.5 },
  content: { padding: 20 },
  section: { fontSize: 15, fontWeight: '700', color: '#00E5A0', marginTop: 24, marginBottom: 8 },
  body: { fontSize: 14, color: '#8A9BB0', lineHeight: 22 },
  sourceCard: { backgroundColor: '#111820', borderRadius: 12, padding: 14, marginTop: 12, borderWidth: 1, borderColor: 'rgba(255,255,255,0.07)' },
  sourceName: { fontSize: 14, fontWeight: '700', color: '#F0F4F8', marginBottom: 4 },
  sourceOrg: { fontSize: 12, color: '#8A9BB0', marginBottom: 6 },
  sourceLink: { fontSize: 11, color: '#00E5A0', textDecorationLine: 'underline' },
  spacer: { height: 40 },
});

export default function SourcesScreen(props) {
  return (
    <ErrorBoundary screenName="SourcesScreen">
      <SourcesScreenInner {...props} />
    </ErrorBoundary>
  );
}
